const form={
    'health issues':[
        "AIDS",
        "alcoholism",
        "allegies",
        "anxiety",
        "asthma",
        "arthritis",
        "chronic fatigue",
        "chemical sensitivities",
        "depression",
        "diabetes",
        "dizzines",
        "drug abuse",
        "headaches",
        "hearing problems",
        "hepatitis a",
        "hepatitis b",
        "hepatitis c",
        "high blood pressure",
        "HIV",
        "memory loss",
        "painful joints",
        "seizures",
        "shortness of breath",
    ],
    services:[
        "Education and Awareness",
        "Grocery Shopping",
        "Hospital Visitation",
        "Meal Delivery",
        "Peer Support for Survivors",
        "Pet Walking",
        "Prayer & Spiritual Support",
        "Support Group",
        "Not sure yet",
    ],
    incomeLevel:[
        "",
        "< $10,000",
        "$10,000-$14,999",
        "$15,000-$24,999",
        "$25,000-$34,999",
        "$35,000-$49,999",
        "$50,000-$74,999",
        "$75,000-$89,999",
        "$90,000+",
    ],
    incomeSource:[
        "",
        "social security (retirement)",
        "alimony",
        "salary",
        "sick leave pay",
        "public assistance",
        "pension",
        "short-term disability",
        "in-kind (room and board)",
        "child support",
        "family/friends support",
        "SSI",
        "other",
    ],
    financialServices:[
        "grocery gift card",
        "gas card",
        "rental assistance",
        "meal assistance",
        "utility assistance",
        "pharmacy card",
        "clothing",
        "not sure yet",
    ]
}
export default form